# Generated by Django 5.2 on 2025-04-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('rarity', models.IntegerField(default=1)),
                ('attack', models.JSONField(blank=True, null=True)),
                ('elements', models.JSONField(blank=True, null=True)),
                ('assets', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
