# Generated by Django 5.2 on 2025-04-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('rank', models.CharField(max_length=20)),
                ('rarity', models.IntegerField()),
                ('defense', models.JSONField(blank=True, null=True)),
                ('resistances', models.JSONField(blank=True, null=True)),
                ('slots', models.JSONField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, null=True)),
                ('armor_set', models.JSONField(blank=True, null=True)),
                ('assets', models.JSONField(blank=True, null=True)),
                ('crafting', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
