# Generated by Django 5.2 on 2025-04-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
